spring.datasource.url=jdbc:postgresql://localhost:5432/hotelapp
spring.datasource.username=hotelapp_user
spring.datasource.password=123
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

apartment.base.price=50
apartment.base.currency=BYN
apartment.base.status=FREE
apartment.status.change=false

