serialized.apartment.path=json/apartments.json
serialized.client.path=json/clients.json

apartment.base.price=50
apartment.base.currency=BYN
apartment.base.status=FREE
apartment.status.change=false

db.driver.name=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/hotelapp
db.username=hotelapp_user
db.password=123
db.pool.size=10